"""10-year anniversary word bank: 250 bilingual cards in three difficulty tiers.

Ranked within each tier by usefulness for learners (most useful first).
Each entry matches ``seed.SEED_CARDS`` minus rarity:
``(word_es, word_en, part_of_speech, gender, example_es, example_en)``.

Selection rules (so every card is fair to catch in both directions):
- one dominant translation — no words whose English has several equally
  common Spanish equivalents (``time`` → tiempo/hora/vez), and vice versa;
- no US/UK spelling splits (``color``/``colour``, ``neighbor``) and no
  untranslatable words (``sobremesa``) since the English side is typed;
- nouns carry their article on both sides (``la casa`` / ``the house``);
  ``gender`` is the grammatical gender (``el agua`` is feminine → ``la``);
- examples stay short enough for one line on the card.

Anniversary-themed words (fiesta, regalo, aniversario, década…) are
mixed into every tier.
"""

type Entry = tuple[str, str, str, str | None, str, str]

BASICO: list[Entry] = [
    ("la casa", "the house", "sustantivo", "la", "Mi casa tiene un jardín.", "My house has a garden."),
    ("el agua", "water", "sustantivo", "la", "Bebo agua fría.", "I drink cold water."),
    ("comer", "to eat", "verbo", None, "Me gusta comer fruta.", "I like to eat fruit."),
    ("hablar", "to speak", "verbo", None, "Quiero hablar español.", "I want to speak Spanish."),
    ("el amigo", "the friend", "sustantivo", "el", "Mi amigo vive cerca.", "My friend lives nearby."),
    ("la familia", "the family", "sustantivo", "la", "Mi familia es grande.", "My family is big."),
    ("el día", "the day", "sustantivo", "el", "Hoy es un buen día.", "Today is a good day."),
    ("la noche", "the night", "sustantivo", "la", "La noche está tranquila.", "The night is quiet."),
    ("grande", "big", "adjetivo", None, "Tienen un perro grande.", "They have a big dog."),
    ("pequeño", "small", "adjetivo", None, "Es un pueblo pequeño.", "It is a small town."),
    ("beber", "to drink", "verbo", None, "Hay que beber agua.", "You have to drink water."),
    ("dormir", "to sleep", "verbo", None, "Quiero dormir ocho horas.", "I want to sleep eight hours."),
    ("vivir", "to live", "verbo", None, "Vivo en una ciudad.", "I live in a city."),
    ("el perro", "the dog", "sustantivo", "el", "El perro corre en el parque.", "The dog runs in the park."),
    ("el gato", "the cat", "sustantivo", "el", "El gato duerme mucho.", "The cat sleeps a lot."),
    ("la madre", "the mother", "sustantivo", "la", "Mi madre cocina muy bien.", "My mother cooks very well."),
    ("el padre", "the father", "sustantivo", "el", "Mi padre trabaja aquí.", "My father works here."),
    ("el hermano", "the brother", "sustantivo", "el", "Mi hermano es alto.", "My brother is tall."),
    ("la hermana", "the sister", "sustantivo", "la", "Mi hermana canta.", "My sister sings."),
    ("el libro", "the book", "sustantivo", "el", "Leo un libro cada mes.", "I read a book every month."),
    ("la escuela", "the school", "sustantivo", "la", "La escuela abre a las ocho.", "The school opens at eight."),
    ("leer", "to read", "verbo", None, "Me encanta leer.", "I love to read."),
    ("escribir", "to write", "verbo", None, "Voy a escribir una carta.", "I am going to write a letter."),
    ("aprender", "to learn", "verbo", None, "Quiero aprender inglés.", "I want to learn English."),
    ("trabajar", "to work", "verbo", None, "Trabajo desde casa.", "I work from home."),
    ("bueno", "good", "adjetivo", None, "Es un buen libro.", "It is a good book."),
    ("malo", "bad", "adjetivo", None, "Hace mal tiempo hoy.", "The weather is bad today."),
    ("nuevo", "new", "adjetivo", None, "Tengo un teléfono nuevo.", "I have a new phone."),
    ("viejo", "old", "adjetivo", None, "El coche es viejo.", "The car is old."),
    ("feliz", "happy", "adjetivo", None, "Estoy muy feliz hoy.", "I am very happy today."),
    ("triste", "sad", "adjetivo", None, "La película es triste.", "The movie is sad."),
    ("la ciudad", "the city", "sustantivo", "la", "La ciudad nunca duerme.", "The city never sleeps."),
    ("la calle", "the street", "sustantivo", "la", "La calle está vacía.", "The street is empty."),
    ("el coche", "the car", "sustantivo", "el", "El coche es rojo.", "The car is red."),
    ("la puerta", "the door", "sustantivo", "la", "Cierra la puerta, por favor.", "Close the door, please."),
    ("la ventana", "the window", "sustantivo", "la", "Abre la ventana.", "Open the window."),
    ("la mesa", "the table", "sustantivo", "la", "La comida está en la mesa.", "The food is on the table."),
    ("la silla", "the chair", "sustantivo", "la", "Siéntate en la silla.", "Sit on the chair."),
    ("la cama", "the bed", "sustantivo", "la", "Mi cama es cómoda.", "My bed is comfortable."),
    ("la cocina", "the kitchen", "sustantivo", "la", "Desayunamos en la cocina.", "We have breakfast in the kitchen."),
    ("el pan", "bread", "sustantivo", "el", "Compro pan cada mañana.", "I buy bread every morning."),
    ("la leche", "milk", "sustantivo", "la", "El café con leche está rico.", "Coffee with milk is tasty."),
    ("el huevo", "the egg", "sustantivo", "el", "Como un huevo al día.", "I eat an egg a day."),
    ("el queso", "cheese", "sustantivo", "el", "Este queso es fuerte.", "This cheese is strong."),
    ("la manzana", "the apple", "sustantivo", "la", "La manzana es verde.", "The apple is green."),
    ("el arroz", "rice", "sustantivo", "el", "El arroz ya está listo.", "The rice is ready."),
    ("la sopa", "the soup", "sustantivo", "la", "La sopa está caliente.", "The soup is hot."),
    ("el café", "coffee", "sustantivo", "el", "Tomo café por la mañana.", "I drink coffee in the morning."),
    ("rojo", "red", "adjetivo", None, "Me gusta el vestido rojo.", "I like the red dress."),
    ("azul", "blue", "adjetivo", None, "El cielo está azul.", "The sky is blue."),
    ("verde", "green", "adjetivo", None, "La hierba es verde.", "The grass is green."),
    ("amarillo", "yellow", "adjetivo", None, "El sol es amarillo.", "The sun is yellow."),
    ("negro", "black", "adjetivo", None, "Tengo un gato negro.", "I have a black cat."),
    ("blanco", "white", "adjetivo", None, "La nieve es blanca.", "Snow is white."),
    ("el sol", "the sun", "sustantivo", "el", "El sol sale temprano.", "The sun rises early."),
    ("la luna", "the moon", "sustantivo", "la", "La luna está llena.", "The moon is full."),
    ("la lluvia", "rain", "sustantivo", "la", "Me gusta la lluvia.", "I like the rain."),
    ("la nieve", "snow", "sustantivo", "la", "La nieve cubre la montaña.", "Snow covers the mountain."),
    ("el viento", "the wind", "sustantivo", "el", "El viento sopla fuerte.", "The wind blows hard."),
    ("el árbol", "the tree", "sustantivo", "el", "El árbol da sombra.", "The tree gives shade."),
    ("la flor", "the flower", "sustantivo", "la", "Te regalo una flor.", "I am giving you a flower."),
    ("el mar", "the sea", "sustantivo", "el", "El mar está tranquilo.", "The sea is calm."),
    ("la playa", "the beach", "sustantivo", "la", "Vamos a la playa.", "Let's go to the beach."),
    ("la montaña", "the mountain", "sustantivo", "la", "Subimos la montaña.", "We climbed the mountain."),
    ("el río", "the river", "sustantivo", "el", "El río es muy largo.", "The river is very long."),
    ("el parque", "the park", "sustantivo", "el", "Jugamos en el parque.", "We play in the park."),
    ("el mercado", "the market", "sustantivo", "el", "El mercado abre los sábados.", "The market opens on Saturdays."),
    ("correr", "to run", "verbo", None, "Corro todas las mañanas.", "I run every morning."),
    ("cantar", "to sing", "verbo", None, "Ella canta muy bien.", "She sings very well."),
    ("bailar", "to dance", "verbo", None, "Vamos a bailar salsa.", "Let's dance salsa."),
    ("cocinar", "to cook", "verbo", None, "Hoy voy a cocinar pasta.", "Today I am going to cook pasta."),
    ("nadar", "to swim", "verbo", None, "Aprendí a nadar de niño.", "I learned to swim as a child."),
    ("viajar", "to travel", "verbo", None, "Quiero viajar a México.", "I want to travel to Mexico."),
    ("comprar", "to buy", "verbo", None, "Voy a comprar pan.", "I am going to buy bread."),
    ("abrir", "to open", "verbo", None, "¿Puedes abrir la puerta?", "Can you open the door?"),
    ("cerrar", "to close", "verbo", None, "Cierran la tienda a las nueve.", "They close the shop at nine."),
    ("ayudar", "to help", "verbo", None, "¿Me puedes ayudar?", "Can you help me?"),
    ("escuchar", "to listen", "verbo", None, "Me gusta escuchar música.", "I like to listen to music."),
    ("la mano", "the hand", "sustantivo", "la", "Levanta la mano.", "Raise your hand."),
    ("la cabeza", "the head", "sustantivo", "la", "Me duele la cabeza.", "My head hurts."),
    ("el ojo", "the eye", "sustantivo", "el", "Tiene un ojo azul.", "He has one blue eye."),
    ("la boca", "the mouth", "sustantivo", "la", "Abre la boca.", "Open your mouth."),
    ("el pájaro", "the bird", "sustantivo", "el", "El pájaro canta al amanecer.", "The bird sings at dawn."),
    ("el pez", "the fish", "sustantivo", "el", "El pez nada en el agua.", "The fish swims in the water."),
    ("el caballo", "the horse", "sustantivo", "el", "El caballo corre rápido.", "The horse runs fast."),
    ("la fiesta", "the party", "sustantivo", "la", "¡La fiesta empieza a las diez!", "The party starts at ten!"),
    ("el regalo", "the gift", "sustantivo", "el", "Este regalo es para ti.", "This gift is for you."),
    ("el pastel", "the cake", "sustantivo", "el", "El pastel es de chocolate.", "The cake is chocolate."),
    ("la vela", "the candle", "sustantivo", "la", "Sopla la vela.", "Blow out the candle."),
    ("la música", "music", "sustantivo", "la", "La música está muy alta.", "The music is very loud."),
    ("el año", "the year", "sustantivo", "el", "Este año fue increíble.", "This year was incredible."),
    ("la semana", "the week", "sustantivo", "la", "La semana pasó rápido.", "The week went by fast."),
    ("el mes", "the month", "sustantivo", "el", "El mes que viene viajo.", "Next month I travel."),
    ("el dinero", "money", "sustantivo", "el", "No tengo dinero.", "I have no money."),
    ("la palabra", "the word", "sustantivo", "la", "Aprendí una palabra nueva.", "I learned a new word."),
    ("el nombre", "the name", "sustantivo", "el", "¿Cuál es tu nombre?", "What is your name?"),
    ("la pregunta", "the question", "sustantivo", "la", "Tengo una pregunta.", "I have a question."),
    ("la respuesta", "the answer", "sustantivo", "la", "La respuesta es fácil.", "The answer is easy."),
    ("fácil", "easy", "adjetivo", None, "El examen fue fácil.", "The exam was easy."),
    ("difícil", "difficult", "adjetivo", None, "Esta palabra es difícil.", "This word is difficult."),
]

INTERMEDIO: list[Entry] = [
    ("recordar", "to remember", "verbo", None, "No recuerdo su nombre.", "I don't remember his name."),
    ("olvidar", "to forget", "verbo", None, "Nunca olvido una cara.", "I never forget a face."),
    ("intentar", "to try", "verbo", None, "Voy a intentar otra vez.", "I am going to try again."),
    ("elegir", "to choose", "verbo", None, "Es difícil elegir.", "It is hard to choose."),
    ("encontrar", "to find", "verbo", None, "No encuentro mis llaves.", "I can't find my keys."),
    ("perder", "to lose", "verbo", None, "No quiero perder el partido.", "I don't want to lose the match."),
    ("ganar", "to win", "verbo", None, "¡Vamos a ganar!", "We are going to win!"),
    ("compartir", "to share", "verbo", None, "Me gusta compartir la comida.", "I like to share food."),
    ("cambiar", "to change", "verbo", None, "Todo puede cambiar.", "Everything can change."),
    ("crecer", "to grow", "verbo", None, "Las plantas crecen rápido.", "The plants grow fast."),
    ("construir", "to build", "verbo", None, "Van a construir una escuela.", "They are going to build a school."),
    ("romper", "to break", "verbo", None, "No rompas el vaso.", "Don't break the glass."),
    ("esconder", "to hide", "verbo", None, "El gato se esconde.", "The cat hides."),
    ("soñar", "to dream", "verbo", None, "Sueño con viajar.", "I dream of traveling."),
    ("mezclar", "to mix", "verbo", None, "Mezcla la harina y el azúcar.", "Mix the flour and the sugar."),
    ("llenar", "to fill", "verbo", None, "Llena el vaso de agua.", "Fill the glass with water."),
    ("susurrar", "to whisper", "verbo", None, "Le susurró un secreto.", "He whispered a secret to her."),
    ("celebrar", "to celebrate", "verbo", None, "Hoy celebramos diez años.", "Today we celebrate ten years."),
    ("el idioma", "the language", "sustantivo", "el", "Hablo tres idiomas.", "I speak three languages."),
    ("el acento", "the accent", "sustantivo", "el", "Tienes un acento bonito.", "You have a nice accent."),
    ("el error", "the mistake", "sustantivo", "el", "Todos cometemos errores.", "We all make mistakes."),
    ("el diccionario", "the dictionary", "sustantivo", "el", "Busca la palabra en el diccionario.", "Look the word up in the dictionary."),
    ("el vocabulario", "vocabulary", "sustantivo", "el", "Tu vocabulario crece cada día.", "Your vocabulary grows every day."),
    ("la pronunciación", "pronunciation", "sustantivo", "la", "Su pronunciación es perfecta.", "Her pronunciation is perfect."),
    ("la comunidad", "the community", "sustantivo", "la", "Esta comunidad es increíble.", "This community is incredible."),
    ("el aniversario", "the anniversary", "sustantivo", "el", "Feliz aniversario a todos.", "Happy anniversary, everyone."),
    ("la celebración", "the celebration", "sustantivo", "la", "La celebración dura un mes.", "The celebration lasts a month."),
    ("la sorpresa", "the surprise", "sustantivo", "la", "¡Qué sorpresa tan bonita!", "What a lovely surprise!"),
    ("el globo", "the balloon", "sustantivo", "el", "El globo voló muy alto.", "The balloon flew very high."),
    ("la invitación", "the invitation", "sustantivo", "la", "Gracias por la invitación.", "Thanks for the invitation."),
    ("el invitado", "the guest", "sustantivo", "el", "Llegó el primer invitado.", "The first guest arrived."),
    ("el brindis", "the toast", "sustantivo", "el", "Un brindis por los diez años.", "A toast to ten years."),
    ("el viaje", "the trip", "sustantivo", "el", "El viaje fue largo.", "The trip was long."),
    ("la verdad", "the truth", "sustantivo", "la", "Dime la verdad.", "Tell me the truth."),
    ("la mentira", "the lie", "sustantivo", "la", "Eso es una mentira.", "That is a lie."),
    ("la salud", "health", "sustantivo", "la", "La salud es lo primero.", "Health comes first."),
    ("la llave", "the key", "sustantivo", "la", "Perdí la llave de casa.", "I lost the house key."),
    ("el espejo", "the mirror", "sustantivo", "el", "Se mira en el espejo.", "She looks in the mirror."),
    ("la almohada", "the pillow", "sustantivo", "la", "Mi almohada es suave.", "My pillow is soft."),
    ("el bolsillo", "the pocket", "sustantivo", "el", "Tengo monedas en el bolsillo.", "I have coins in my pocket."),
    ("el paraguas", "the umbrella", "sustantivo", "el", "Lleva el paraguas, va a llover.", "Take the umbrella, it will rain."),
    ("la cuchara", "the spoon", "sustantivo", "la", "Necesito una cuchara.", "I need a spoon."),
    ("el tenedor", "the fork", "sustantivo", "el", "El tenedor está sucio.", "The fork is dirty."),
    ("el cuchillo", "the knife", "sustantivo", "el", "Corta el pan con el cuchillo.", "Cut the bread with the knife."),
    ("el hielo", "ice", "sustantivo", "el", "Pon hielo en el vaso.", "Put ice in the glass."),
    ("el fuego", "the fire", "sustantivo", "el", "El fuego nos calienta.", "The fire keeps us warm."),
    ("el humo", "smoke", "sustantivo", "el", "Sale humo de la chimenea.", "Smoke comes out of the chimney."),
    ("el puente", "the bridge", "sustantivo", "el", "Cruzamos el puente al amanecer.", "We crossed the bridge at dawn."),
    ("la nube", "the cloud", "sustantivo", "la", "Una nube cubrió el sol.", "A cloud covered the sun."),
    ("el bosque", "the forest", "sustantivo", "el", "Nos perdimos en el bosque.", "We got lost in the forest."),
    ("la isla", "the island", "sustantivo", "la", "Vivimos en una isla.", "We live on an island."),
    ("el desierto", "the desert", "sustantivo", "el", "El desierto es muy seco.", "The desert is very dry."),
    ("la cueva", "the cave", "sustantivo", "la", "La cueva está oscura.", "The cave is dark."),
    ("la ola", "the wave", "sustantivo", "la", "Una ola enorme llegó.", "A huge wave arrived."),
    ("la tormenta", "the storm", "sustantivo", "la", "Viene una tormenta.", "A storm is coming."),
    ("el trueno", "thunder", "sustantivo", "el", "El trueno asustó al perro.", "The thunder scared the dog."),
    ("el relámpago", "lightning", "sustantivo", "el", "El relámpago iluminó el cielo.", "The lightning lit up the sky."),
    ("la arena", "sand", "sustantivo", "la", "La arena está caliente.", "The sand is hot."),
    ("la hoja", "the leaf", "sustantivo", "la", "Cayó una hoja del árbol.", "A leaf fell from the tree."),
    ("la raíz", "the root", "sustantivo", "la", "El árbol tiene raíces profundas.", "The tree has deep roots."),
    ("la semilla", "the seed", "sustantivo", "la", "Planté una semilla.", "I planted a seed."),
    ("el atardecer", "the sunset", "sustantivo", "el", "El atardecer fue precioso.", "The sunset was beautiful."),
    ("la mariposa", "the butterfly", "sustantivo", "la", "Una mariposa se posó en la flor.", "A butterfly landed on the flower."),
    ("el cuervo", "the crow", "sustantivo", "el", "El cuervo graznó al amanecer.", "The crow cawed at dawn."),
    ("la abeja", "the bee", "sustantivo", "la", "La abeja hace miel.", "The bee makes honey."),
    ("el conejo", "the rabbit", "sustantivo", "el", "El conejo come zanahorias.", "The rabbit eats carrots."),
    ("orgulloso", "proud", "adjetivo", None, "Estoy orgulloso de ti.", "I am proud of you."),
    ("celoso", "jealous", "adjetivo", None, "Mi perro es muy celoso.", "My dog is very jealous."),
    ("cansado", "tired", "adjetivo", None, "Estoy cansado hoy.", "I am tired today."),
    ("asustado", "scared", "adjetivo", None, "El niño está asustado.", "The child is scared."),
    ("valiente", "brave", "adjetivo", None, "Fuiste muy valiente.", "You were very brave."),
    ("tímido", "shy", "adjetivo", None, "Es tímido con la gente nueva.", "He is shy with new people."),
    ("amable", "kind", "adjetivo", None, "Gracias, eres muy amable.", "Thanks, you are very kind."),
    ("perezoso", "lazy", "adjetivo", None, "El gato es perezoso.", "The cat is lazy."),
    ("ruidoso", "noisy", "adjetivo", None, "El bar es ruidoso.", "The bar is noisy."),
    ("tranquilo", "calm", "adjetivo", None, "El lago está tranquilo.", "The lake is calm."),
    ("extraño", "strange", "adjetivo", None, "Escuché un ruido extraño.", "I heard a strange noise."),
    ("peligroso", "dangerous", "adjetivo", None, "Ese camino es peligroso.", "That road is dangerous."),
    ("profundo", "deep", "adjetivo", None, "El lago es profundo.", "The lake is deep."),
    ("oscuro", "dark", "adjetivo", None, "El cuarto está oscuro.", "The room is dark."),
    ("suave", "soft", "adjetivo", None, "La manta es suave.", "The blanket is soft."),
    ("alegre", "cheerful", "adjetivo", None, "Ella siempre está alegre.", "She is always cheerful."),
    ("brillante", "bright", "adjetivo", None, "Una estrella brillante.", "A bright star."),
    ("lleno", "full", "adjetivo", None, "El vaso está lleno.", "The glass is full."),
    ("vacío", "empty", "adjetivo", None, "El tren llegó vacío.", "The train arrived empty."),
    ("juntos", "together", "adverbio", None, "Aprendemos juntos.", "We learn together."),
    ("siempre", "always", "adverbio", None, "Siempre llego tarde.", "I always arrive late."),
    ("nunca", "never", "adverbio", None, "Nunca es tarde para aprender.", "It is never too late to learn."),
    ("todavía", "still", "adverbio", None, "Todavía estoy aquí.", "I am still here."),
    ("despacio", "slowly", "adverbio", None, "Habla más despacio, por favor.", "Speak more slowly, please."),
]

AVANZADO: list[Entry] = [
    ("la década", "the decade", "sustantivo", "la", "Una década juntos.", "A decade together."),
    ("el hito", "the milestone", "sustantivo", "el", "Diez años es un gran hito.", "Ten years is a big milestone."),
    ("el legado", "the legacy", "sustantivo", "el", "Su legado sigue vivo.", "Their legacy lives on."),
    ("la gratitud", "gratitude", "sustantivo", "la", "Te escribo con gratitud.", "I write to you with gratitude."),
    ("la nostalgia", "nostalgia", "sustantivo", "la", "Siento nostalgia por mi país.", "I feel nostalgia for my country."),
    ("el porvenir", "the future", "sustantivo", "el", "El porvenir es brillante.", "The future is bright."),
    ("el desafío", "the challenge", "sustantivo", "el", "Aprender un idioma es un desafío.", "Learning a language is a challenge."),
    ("la hazaña", "the feat", "sustantivo", "la", "Fue una verdadera hazaña.", "It was a true feat."),
    ("el anhelo", "longing", "sustantivo", "el", "Su anhelo era volver.", "Her longing was to return."),
    ("la ternura", "tenderness", "sustantivo", "la", "Lo miró con ternura.", "She looked at him with tenderness."),
    ("la valentía", "bravery", "sustantivo", "la", "Admiro tu valentía.", "I admire your bravery."),
    ("la tenacidad", "tenacity", "sustantivo", "la", "Con tenacidad, todo es posible.", "With tenacity, anything is possible."),
    ("el rencor", "resentment", "sustantivo", "el", "No guardo rencor.", "I hold no resentment."),
    ("la inquietud", "restlessness", "sustantivo", "la", "Una inquietud extraña lo invadió.", "A strange restlessness overcame him."),
    ("la torpeza", "clumsiness", "sustantivo", "la", "Perdona mi torpeza.", "Forgive my clumsiness."),
    ("la pereza", "laziness", "sustantivo", "la", "Hoy me gana la pereza.", "Today laziness wins."),
    ("el crepúsculo", "the twilight", "sustantivo", "el", "Caminamos durante el crepúsculo.", "We walked during the twilight."),
    ("el amanecer", "the dawn", "sustantivo", "el", "Salimos antes del amanecer.", "We left before dawn."),
    ("el resplandor", "the glow", "sustantivo", "el", "El resplandor de la ciudad.", "The glow of the city."),
    ("el susurro", "the whisper", "sustantivo", "el", "Oí un susurro en la oscuridad.", "I heard a whisper in the dark."),
    ("el murmullo", "the murmur", "sustantivo", "el", "El murmullo del río.", "The murmur of the river."),
    ("el bullicio", "the bustle", "sustantivo", "el", "Me encanta el bullicio del mercado.", "I love the bustle of the market."),
    ("el escalofrío", "the shiver", "sustantivo", "el", "Sentí un escalofrío.", "I felt a shiver."),
    ("el bostezo", "the yawn", "sustantivo", "el", "Un bostezo es contagioso.", "A yawn is contagious."),
    ("el parpadeo", "the blink", "sustantivo", "el", "Pasó en un parpadeo.", "It happened in a blink."),
    ("el atisbo", "the glimpse", "sustantivo", "el", "Un atisbo de esperanza.", "A glimpse of hope."),
    ("el remolino", "the whirlpool", "sustantivo", "el", "El barco cayó en un remolino.", "The boat fell into a whirlpool."),
    ("la vorágine", "the maelstrom", "sustantivo", "la", "La vorágine de la ciudad.", "The maelstrom of the city."),
    ("la tregua", "the truce", "sustantivo", "la", "Firmaron una tregua.", "They signed a truce."),
    ("la serendipia", "serendipity", "sustantivo", "la", "Nos conocimos por serendipia.", "We met by serendipity."),
    ("la brújula", "the compass", "sustantivo", "la", "Sin brújula, nos perdimos.", "Without a compass, we got lost."),
    ("el faro", "the lighthouse", "sustantivo", "el", "El faro guía a los barcos.", "The lighthouse guides the ships."),
    ("la colmena", "the beehive", "sustantivo", "la", "La colmena está llena de miel.", "The beehive is full of honey."),
    ("la luciérnaga", "the firefly", "sustantivo", "la", "Una luciérnaga brilla en la noche.", "A firefly glows in the night."),
    ("el colibrí", "the hummingbird", "sustantivo", "el", "El colibrí bebe néctar.", "The hummingbird drinks nectar."),
    ("el murciélago", "the bat", "sustantivo", "el", "El murciélago vuela de noche.", "The bat flies at night."),
    ("la ardilla", "the squirrel", "sustantivo", "la", "La ardilla guarda nueces.", "The squirrel stores nuts."),
    ("el búho", "the owl", "sustantivo", "el", "El búho nos observa.", "The owl watches us."),
    ("el caracol", "the snail", "sustantivo", "el", "El caracol avanza despacio.", "The snail moves slowly."),
    ("agradecer", "to thank", "verbo", None, "Quiero agradecer a todos.", "I want to thank everyone."),
    ("merecer", "to deserve", "verbo", None, "Mereces lo mejor.", "You deserve the best."),
    ("desperdiciar", "to waste", "verbo", None, "No desperdicies la comida.", "Don't waste food."),
    ("vislumbrar", "to glimpse", "verbo", None, "Vislumbramos la costa.", "We glimpsed the coast."),
    ("tropezar", "to trip", "verbo", None, "Tropecé con una piedra.", "I tripped on a stone."),
    ("derretir", "to melt", "verbo", None, "El sol derrite la nieve.", "The sun melts the snow."),
    ("hervir", "to boil", "verbo", None, "Hierve el agua para el té.", "Boil the water for the tea."),
    ("regañar", "to scold", "verbo", None, "No me regañes.", "Don't scold me."),
    ("presumir", "to brag", "verbo", None, "Le gusta presumir de su coche.", "He likes to brag about his car."),
    ("fingir", "to pretend", "verbo", None, "No finjas que no lo sabes.", "Don't pretend you don't know."),
    ("suspirar", "to sigh", "verbo", None, "Suspiró y cerró los ojos.", "She sighed and closed her eyes."),
    ("efímero", "ephemeral", "adjetivo", None, "La belleza del momento fue efímera.", "The beauty of the moment was ephemeral."),
    ("inefable", "ineffable", "adjetivo", None, "Sintió una alegría inefable.", "He felt an ineffable joy."),
    ("imprescindible", "essential", "adjetivo", None, "El agua es imprescindible.", "Water is essential."),
    ("ineludible", "unavoidable", "adjetivo", None, "Fue un cambio ineludible.", "It was an unavoidable change."),
    ("entrañable", "endearing", "adjetivo", None, "Es un recuerdo entrañable.", "It is an endearing memory."),
    ("sigiloso", "stealthy", "adjetivo", None, "El gato es sigiloso.", "The cat is stealthy."),
    ("minucioso", "meticulous", "adjetivo", None, "Hizo un trabajo minucioso.", "He did meticulous work."),
    ("testarudo", "stubborn", "adjetivo", None, "Mi abuelo es testarudo.", "My grandfather is stubborn."),
    ("deslumbrante", "dazzling", "adjetivo", None, "Una sonrisa deslumbrante.", "A dazzling smile."),
    ("insólito", "unusual", "adjetivo", None, "Fue un día insólito.", "It was an unusual day."),
]

# Difficulty tier → pool rarity (1–5 scale used by vocab_card_pool).
TIER_RARITY = {"básico": 1, "intermedio": 3, "avanzado": 5}
TIERS: dict[str, list[Entry]] = {"básico": BASICO, "intermedio": INTERMEDIO, "avanzado": AVANZADO}
