"""
Ask cog — owner-only Gemini Q&A with paginated responses.
"""
import asyncio
import logging

import discord
from discord.ext import commands

from base_cog import BaseCog
from cogs.utils.gemini import GeminiError
from cogs.utils.visibility import VisibilityView as BaseVisibilityView

from .prompts import ASK_PROMPT

logger = logging.getLogger(__name__)

PAGE_CONTENT_LIMIT = 3900
GEMINI_TIMEOUT = 30


def split_response(text: str) -> list[str]:
    """Split text into pages that fit in embed descriptions."""
    if len(text) <= PAGE_CONTENT_LIMIT:
        return [text]

    pages = []
    remaining = text

    while remaining:
        if len(remaining) <= PAGE_CONTENT_LIMIT:
            pages.append(remaining)
            break

        chunk = remaining[:PAGE_CONTENT_LIMIT]

        split_idx = chunk.rfind('\n```')
        if split_idx > PAGE_CONTENT_LIMIT // 2:
            split_idx += 1
        elif (idx := chunk.rfind('\n\n')) > PAGE_CONTENT_LIMIT // 2 or (idx := chunk.rfind('\n')) > PAGE_CONTENT_LIMIT // 2:
            split_idx = idx
        else:
            split_idx = PAGE_CONTENT_LIMIT

        pages.append(remaining[:split_idx])
        remaining = remaining[split_idx:].lstrip('\n')

    return pages


def _build_ask_embed(pages: list[str], question: str, page_idx: int = 0) -> discord.Embed:
    title = question[:256]
    embed = discord.Embed(title=title, description=pages[page_idx], color=0x5865F2)
    footer = "Generated by AI"
    if len(pages) > 1:
        footer += f" — Page {page_idx + 1}/{len(pages)}"
    embed.set_footer(text=footer)
    return embed


class PageView(discord.ui.View):
    """Pagination buttons for multi-page responses."""

    def __init__(self, pages: list[str], question: str, author_id: int):
        super().__init__(timeout=300)
        self.pages = pages
        self.question = question
        self.author_id = author_id
        self.current = 0

    def build_embed(self) -> discord.Embed:
        return _build_ask_embed(self.pages, self.question, self.current)

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        return interaction.user.id == self.author_id

    @discord.ui.button(label='◀', style=discord.ButtonStyle.secondary)
    async def prev_page(self, interaction: discord.Interaction, button: discord.ui.Button):
        if self.current > 0:
            self.current -= 1
        await interaction.response.edit_message(embed=self.build_embed(), view=self)

    @discord.ui.button(label='▶', style=discord.ButtonStyle.secondary)
    async def next_page(self, interaction: discord.Interaction, button: discord.ui.Button):
        if self.current < len(self.pages) - 1:
            self.current += 1
        await interaction.response.edit_message(embed=self.build_embed(), view=self)


class AskCog(BaseCog):
    """Owner-only Gemini Q&A."""

    @commands.command(name='ask')
    @commands.is_owner()
    async def ask(self, ctx: commands.Context, *, question: str):
        """
        Ask Gemini anything. Owner only.

        Usage: $ask <question>
        """
        if self.bot.gemini is None:
            await ctx.send("Gemini is not configured on this bot.")
            return

        processing = await ctx.send("Thinking...")

        try:
            text = await asyncio.wait_for(
                self.bot.gemini.run(ASK_PROMPT, question),
                timeout=GEMINI_TIMEOUT,
            )
        except TimeoutError:
            await processing.edit(content=f"Gemini didn't respond within {GEMINI_TIMEOUT}s. Try again.")
            return
        except GeminiError as e:
            logger.warning("Ask Gemini error code=%s: %s", e.code, e.message)
            await processing.edit(content=e.user_message)
            return
        except Exception:
            logger.error("Ask command unexpected error", exc_info=True)
            await processing.edit(content="Something went wrong. Please try again later.")
            return

        if not text:
            await processing.edit(content="Gemini returned an empty response.")
            return

        pages = split_response(text)

        def _embed_kwargs():
            if len(pages) == 1:
                return {'embed': _build_ask_embed(pages, question)}
            pv = PageView(pages, question, ctx.author.id)
            return {'embed': pv.build_embed(), 'view': pv}

        async def on_public(cmd_msg):
            kwargs = {**_embed_kwargs(), 'mention_author': False}
            if cmd_msg:
                await cmd_msg.reply(**kwargs)
            else:
                kwargs.pop('mention_author', None)
                await ctx.channel.send(**kwargs)

        async def on_private(interaction):
            await interaction.response.send_message(**_embed_kwargs(), ephemeral=True)

        view = BaseVisibilityView(
            author_id=ctx.author.id,
            command_message=ctx.message,
            on_public=on_public,
            on_private=on_private,
        )
        msg = await processing.edit(content="Ready. How do you want to send it?", view=view)
        view.prompt_message = msg or processing


async def setup(bot: commands.Bot):
    if bot.gemini is None:
        logger.info("bot.gemini is None — AskCog will not load")
        return
    await bot.add_cog(AskCog(bot))
