"""
Ask cog — owner-only Gemini Q&A with paginated responses.
"""
import logging
import os

import discord
from discord.ext import commands
from google import genai
from google.genai import types

from base_cog import BaseCog

logger = logging.getLogger(__name__)

# Discord embed description limit
EMBED_LIMIT = 4096
# Leave room for page indicator in footer
PAGE_CONTENT_LIMIT = 3900


def split_response(text: str) -> list[str]:
    """Split text into pages that fit in embed descriptions.

    Tries to break on code block boundaries, then blank lines, then
    any newline, falling back to hard cut.
    """
    if len(text) <= PAGE_CONTENT_LIMIT:
        return [text]

    pages = []
    remaining = text

    while remaining:
        if len(remaining) <= PAGE_CONTENT_LIMIT:
            pages.append(remaining)
            break

        chunk = remaining[:PAGE_CONTENT_LIMIT]

        # Try to split at a code block boundary (```)
        split_idx = chunk.rfind('\n```')
        if split_idx > PAGE_CONTENT_LIMIT // 2:
            split_idx += 1  # keep the newline with the previous page
        # Try blank line
        elif (idx := chunk.rfind('\n\n')) > PAGE_CONTENT_LIMIT // 2:
            split_idx = idx
        # Try any newline
        elif (idx := chunk.rfind('\n')) > PAGE_CONTENT_LIMIT // 2:
            split_idx = idx
        else:
            split_idx = PAGE_CONTENT_LIMIT

        pages.append(remaining[:split_idx])
        remaining = remaining[split_idx:].lstrip('\n')

    return pages


class PageView(discord.ui.View):
    """Pagination buttons for multi-page responses."""

    def __init__(self, pages: list[str], question: str, author_id: int):
        super().__init__(timeout=300)
        self.pages = pages
        self.question = question
        self.author_id = author_id
        self.current = 0

    def build_embed(self) -> discord.Embed:
        embed = discord.Embed(
            description=self.pages[self.current],
            color=0x5865F2,
        )
        if len(self.question) > 200:
            title = self.question[:197] + "..."
        else:
            title = self.question
        embed.title = title

        footer = "Generated by AI"
        if len(self.pages) > 1:
            footer += f" — Page {self.current + 1}/{len(self.pages)}"
        embed.set_footer(text=footer)
        return embed

    @discord.ui.button(label='◀', style=discord.ButtonStyle.secondary)
    async def prev_page(self, interaction: discord.Interaction, button: discord.ui.Button):
        if interaction.user.id != self.author_id:
            return
        if self.current > 0:
            self.current -= 1
            await interaction.response.edit_message(embed=self.build_embed(), view=self)
        else:
            await interaction.response.defer()

    @discord.ui.button(label='▶', style=discord.ButtonStyle.secondary)
    async def next_page(self, interaction: discord.Interaction, button: discord.ui.Button):
        if interaction.user.id != self.author_id:
            return
        if self.current < len(self.pages) - 1:
            self.current += 1
            await interaction.response.edit_message(embed=self.build_embed(), view=self)
        else:
            await interaction.response.defer()


class AskCog(BaseCog):
    """Owner-only Gemini Q&A."""

    def __init__(self, bot: commands.Bot):
        super().__init__(bot)
        api_key = os.getenv('GEMINI_API_KEY')
        if not api_key:
            raise ValueError("GEMINI_API_KEY environment variable is required")
        self.client = genai.Client(api_key=api_key)
        self.model_name = 'gemini-2.0-flash-lite'

    @commands.command(name='ask')
    @commands.is_owner()
    async def ask(self, ctx: commands.Context, *, question: str):
        """
        Ask Gemini anything. Owner only.

        Usage: $ask <question>
        """
        processing = await ctx.send("Thinking...")

        try:
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=question,
                config=types.GenerateContentConfig(
                    temperature=0.7,
                    max_output_tokens=4096,
                ),
            )

            text = response.text
            if not text:
                await processing.edit(content="Gemini returned an empty response.")
                return

            pages = split_response(text)

            if len(pages) == 1:
                embed = discord.Embed(
                    title=question[:256],
                    description=pages[0],
                    color=0x5865F2,
                )
                embed.set_footer(text="Generated by AI")
                await processing.edit(content=None, embed=embed)
            else:
                view = PageView(pages, question, ctx.author.id)
                await processing.edit(content=None, embed=view.build_embed(), view=view)

        except Exception as e:
            logger.error(f"Ask command error: {e}", exc_info=True)
            error_str = str(e).lower()
            if any(k in error_str for k in ('safety', 'blocked')):
                await processing.edit(content="Response blocked by content policy.")
            elif any(k in error_str for k in ('rate', 'quota', '429')):
                await processing.edit(content="Rate limited. Try again in a minute.")
            else:
                await processing.edit(content=f"Error: {e}")


async def setup(bot: commands.Bot):
    await bot.add_cog(AskCog(bot))
