"""
Hardcoded word lists for seeding practice cards.
"""

SEED_WORDS = {
    "spanish": [
        {"word": "hablar", "translation": "to speak"},
        {"word": "comer", "translation": "to eat"},
        {"word": "vivir", "translation": "to live"},
        {"word": "trabajar", "translation": "to work"},
        {"word": "estudiar", "translation": "to study"},
        {"word": "caminar", "translation": "to walk"},
        {"word": "correr", "translation": "to run"},
        {"word": "escribir", "translation": "to write"},
        {"word": "leer", "translation": "to read"},
        {"word": "escuchar", "translation": "to listen"},
        {"word": "casa", "translation": "house"},
        {"word": "libro", "translation": "book"},
        {"word": "agua", "translation": "water"},
        {"word": "comida", "translation": "food"},
        {"word": "tiempo", "translation": "time / weather"},
        {"word": "grande", "translation": "big"},
        {"word": "pequeno", "translation": "small"},
        {"word": "bueno", "translation": "good"},
        {"word": "malo", "translation": "bad"},
        {"word": "feliz", "translation": "happy"},
    ],
    "english": [
        {"word": "speak", "translation": "hablar"},
        {"word": "eat", "translation": "comer"},
        {"word": "live", "translation": "vivir"},
        {"word": "work", "translation": "trabajar"},
        {"word": "study", "translation": "estudiar"},
        {"word": "walk", "translation": "caminar"},
        {"word": "run", "translation": "correr"},
        {"word": "write", "translation": "escribir"},
        {"word": "read", "translation": "leer"},
        {"word": "listen", "translation": "escuchar"},
        {"word": "house", "translation": "casa"},
        {"word": "book", "translation": "libro"},
        {"word": "water", "translation": "agua"},
        {"word": "food", "translation": "comida"},
        {"word": "weather", "translation": "tiempo"},
        {"word": "big", "translation": "grande"},
        {"word": "small", "translation": "pequeno"},
        {"word": "good", "translation": "bueno"},
        {"word": "bad", "translation": "malo"},
        {"word": "happy", "translation": "feliz"},
    ],
}
